### ISSUE TITLE
about install

### ISSUE THREAD

**Issue by jnbai517** [zhangmwg/ns3-gym-multiagent#2]
I download ZIP file and put it in ns3-3.29/contrib/. After ./waf configure and ./waf , the terminal tells me that "Could not find a task generator for the name ns3-xx(this file name)" . 
So, how can I install it?

**Comment by zhangmwg** [comment]
Please refer to https://github.com/tkn-tub/ns3-gym. Zm W ***@***.*** 签名由 网易邮箱大师 定制 On 09/20/2021 16:25, bajiaoyu517 wrote: I download ZIP file and put it in ns3-3.29/contrib/. After ./waf configure and ./waf , the terminal tells me that "Could not find a task generator for the name ns3-xx(this file name)" . So, how can I install it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jnbai517** [comment]
> Please refer to https://github.com/tkn-tub/ns3-gym. Zm W ***@***.*** 签名由 网易邮箱大师 定制 On 09/20/2021 16:25, bajiaoyu517 wrote: I download ZIP file and put it in ns3-3.29/contrib/. After ./waf configure and ./waf , the terminal tells me that "Could not find a task generator for the name ns3-xx(this file name)" . So, how can I install it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

thank you!
