### ISSUE TITLE
Match node with agent

### ISSUE THREAD

**Issue by jnbai517** [zhangmwg/ns3-gym-multiagent#3]
I appreciate your work very much.

But I want to know, how can I match the node and agent one by one in this ns3-gym-multiagent environment ?

Thank you.

**Comment by jnbai517** [comment]
In README.md ———" the nodes in the network can be completely regarded as independent agents, which have their own states, observations, and rewards." 

But how to realize it? (Or whether there are example codes ?)

**Comment by zhangmwg** [comment]
In ns3-multiagent, a node is regarded as an Agent, and the state and action space of the Agent is constructed through initial communication, which can be adjusted through communication. In NS3-multiagent, there is a one-to-one correspondence between nodes and agents, which is realized by ZMQ and Protocol Buffers. You can view the details in model: https://github.com/zhangmwg/ns3-gym-multiagent/tree/master/model

This is a simple test that does not involve any algorithms. https://github.com/zhangmwg/ns3-gym-multiagent/tree/master/examples/multigym or https://github.com/zhangmwg/ns3-gym-multiagent/tree/master/examples/multi-agent

You can use any ML or RL algorithms.



At 2021-10-10 14:43:45, "bajiaoyu517" ***@***.***> wrote:

I appreciate your work very much.

But I want to know, how can I match the node and agent one by one in this ns3-gym-multiagent environment ?

Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
